# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    begin
    gradle(task: "test")
    app_pool = sh("curl -F 'file=@/home/deepika.m@TA.COM/Downloads/basset-mobile/android/app/build/outputs/apk/release/app-release.apk' -X POST -k https://apps.teamta.net/uploadbinary.php")
    inter_=app_pool.to_s
    sh("touch curl_slack.log")
    sh("echo '#{inter_}' >> curl_slack.log")
    real_link = sh("tail -1 curl_slack.log")
    trimStr = (real_link.to_s).lstrip
    trimedStringLink = ("(#{trimStr})").delete("\n")
    gitMsg    = sh("git log -1 --pretty=%B" )
  end


  end

 
end
